export const IMAGE_RESOLUTIONS = {
  STANDARD_LARGE: "standard_large",
  STANDARD_FANTASTIC: "standard_fantastic",
};

export const IMAGE_SIZES = {
  [IMAGE_RESOLUTIONS.STANDARD_LARGE]: 100,
  [IMAGE_RESOLUTIONS.STANDARD_FANTASTIC]: 250,
};
